version: '3.7'

services:
  advisory:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "88:88"
      - "8888:8888"
    command: "uvicorn main:app --reload --host 0.0.0.0 --port 88 && jupyter lab --ip=0.0.0.0 --allow-root --port 8888"
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=123qwe123
      - DB_DATABASE=advisory
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=123qwe123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=advisory
    volumes:
      - /docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - "42121:5432"
